### ISSUE TITLE
1FF name pledge

### ISSUE THREAD

**Issue by vcrazy** [RiverArts/ShoppingList#1]
Hello, @1FF

I am representing another 1FF organization and we'd like to contribute to the open-source community by starting a company page and uploading some of our already made repositories.
As I see, your repositories are empty but the name is taken :(

What do you think? Could you be so kind to release the name 1FF for us?
The open-source community and I will be very very thankful.

Thanks in advance,
Vihren

**Comment by RiverArts** [comment]
Done

2018-08-17 17:00 GMT+02:00 vcrazy <notifications@github.com>:

**Comment by vihrenganev** [comment]
Thanks a lot!
My team and I are wishing you all the best!
